spring:
  application:
    name: provider
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848 #127.0.0.1:8848 #192.168.200.39:8848
dubbo:
  registry:
    address: spring-cloud://localhost
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.haigeek.provider.service
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
server:
  port: 8081