spring:
  application:
    name: consumer
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848 #192.168.200.39:8848
dubbo:
  registry:
    address: spring-cloud://localhost